# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    http_client:
        max_host_connections: 10
        default_options:
            headers: { 'X-Powered-By': 'ACME App' }
            max_redirects: 7
            
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true
    
    serializer:
        enabled: true
        mapping: 
            paths: ['%kernel.project_dir%/config/serializer/']
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
