App\Entity\Club:
  properties:
    name:
      - NotBlank: ~ 
      - Length: 
          min: 2
          max: 50
          minMessage: 'Your first name must be at least {{ limit }} characters long'
          maxMessage: 'Your first name cannot be longer than {{ limit }} characters'

    budget:
      - NotBlank: ~ 
      - GreaterThan: 0
     
        
      
     